server:
  port: 6666
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    port-header: x-forwarded-port
    protocol-header: x-forwarded-proto
spring:
  datasource:
    url: jdbc:mysql://172.16.13.165:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    open-in-view: true
  redis:
    host: vm-131
    port: 6379
    timeout: 1500s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    com.mye: debug
    org.hibernate.SQL: debug